src/Elmish/React/Import.purs
A small change motivated by the same discussion that started https://github.com/collegevine/purescript-elmish/pull/1. Namely that having `id` readily available in `CommonProps` leads to bad design.
Corresponding CV change at https://github.com/collegevine/cv/pull/2787.
=> Remove id from CommonProps

CHANGELOG.md, bower.json, elmish.dhall, package-lock.json, package.json, src/Elmish/Foreign.purs
One minor breaking change hit us: apparently the structure of `Prim` has changed, which forced me to upgrade `typelevel-prelude`, and while I was at it, I also upgraded all the other dependencies to their latest versions.
=> Upgrade to PureScript 0.13.0

CHANGELOG.md, package-lock.json, src/Elmish.purs, src/Elmish/Component.purs, src/Elmish/Dispatch.purs
When using Elmish, we frequently end up using `bimap` and contravariant operators, so this PR reexports them from the root `Elmish` module to cut down on imports at use sites.
=> Convenience reexports

CHANGELOG.md, src/Elmish.purs, src/Elmish/Component.purs
This gives the `Transition` type a `Bind` instance, so we can use monadic syntax for collecting effects. See comments [on `fork`](https://github.com/collegevine/purescript-elmish/pull/15/files#diff-12c7a835f986da1ebf52811a88f19bbfR72) and [on `Transition`](https://github.com/collegevine/purescript-elmish/pull/15/files#diff-12c7a835f986da1ebf52811a88f19bbfR35).
=> Transition Bind instance

CHANGELOG.md, src/Elmish/Boot.purs
As we added support for SSR, we kind of dropped the simplest use case - where the `main` function of the bundle is supposed to do all the work without any assistance from JS embedded in the page or other such nonsense.
This PR restores such support.
=> Add support for the simplest (toy) entry point

src/Elmish/React.js
While working on upgrading our JS bundler I realized that this import of `react-dom/server` wasn't actually safe. When the bundler is instructed to evict this module from the bundle, `require`ing it doesn't return `null` or `undefined`, it returns an empty object. And this would lead to `exports.renderToString = undefined`, which would be bad if it was called from PureScript.
Fortunately this doesn't really matter that much, since we're never actually calling that function from the browser. Still, better safe than sorry :-)
=> Make import of react-dom/server actually safe

CHANGELOG.md, src/Elmish/Component.purs
We have been sort-of relying on the notion that any effects produced by `fork`/`forkVoid`/`forkMaybe` run asynchronously, but turns out that is not actually the case. 
In reality, PureScript's implementation of `Aff` is carefully crafted not to introduce unnecessary asynchrony in cases where it's not actually required (e.g. waiting on promises or timeouts). In retrospect this makes much sense: if every `bind` in an `Aff` computation was actually async, the computation would be super slow. 
But to my great shame 🤦, this fact has escaped me until recently, when I decided to investigate the slowness of CV Schools Hub. Turns out most of the slowness comes from forking a lot of messages on every interaction, many of which cause heavy stuff to happen, such as school list filtering. Since all …
=> Run commands asynchronously

src/Elmish/Component.purs
When we originally empowered `Transition`, we implemented up to `Bind`, but never implemented `Monad`.
`Bind` alone is enough for using the `do` notation, but the absence of `Monad` turns out to be preventing more complex stuff, such as monad transformers.
=> Transition is now a Monad

bower.json
`debug` v5.0.0 is out, and I've moved it over to your dev dependencies as I am assuming it shouldn't be used in the published library code. Also see:
https://github.com/purescript/package-sets/pull/863
=> Update debug dependency for v5.0.0

CHANGELOG.md, src/Elmish.purs, src/Elmish/Boot.purs, src/Elmish/Component.purs, src/Elmish/Dispatch.purs, src/Elmish/Foreign.purs, src/Elmish/JsCallback.purs
This PR renames `DispatchMsgFn` to `Dispatch` and changes it from a custom type to alias for `msg -> Effect Unit`. 
The original idea behind making it a custom type was that it could report not only messages originating from the dark JS underworld, but also errors due to mistyped event parameters. This feature was seen as necessary in the early days, when we had a lot of JS and JSX code and it would sometimes contain bugs, giving us unexpected types. 
However, this did not work out in practice: even in those dark times I can only remember a couple of cases where this validation logic actually caught a bug. And today we have moved to PureScript-written views entirely, completely obviating the need for parameter validation. So this error-reporting feature is now completely useless, yet it …
=> Simplify Dispatch drastically

CHANGELOG.md, src/Elmish/Foreign.purs, test/Foreign.purs
Added `CanReceiveFromJavaScript (Object a)` instance for any `a`. Previously only this worked for `Object Foreign`, and this turns out to be very inconvenient in practice.
=> CanReceiveFromJavaScript instance for 'Object a'

CHANGELOG.md, src/Elmish.purs, src/Elmish/Boot.purs, src/Elmish/Component.purs
Renames `ComponentDef` to `ComponentDef'` and `Transition` to `Transition'` so that `ComponentDef` and `Transition` can be aliases where the monad is `Aff`. Using `Aff` by default should be more beginner-friendly.
=> Use Aff by default

.github/workflows/build.yml, package-lock.json, package.json, packages.dhall, test.dhall, test/Component.purs, test/Main.js, test/Main.purs
Only one small test, just to establish a working test setup with Enzyme.
=> Enzyme-powered integration tests

CHANGELOG.md, packages.dhall, src/Elmish/Component.js, src/Elmish/Component.purs, src/Elmish/React.js, src/Elmish/React.purs, src/Elmish/State.purs, test/Component.purs, test/Examples/Counter.purs, test/LocalState.purs, test/Main.purs
Now that we have Enzyme-powered tests, I can finally write a test for this bug to make sure I got the repro right, and then fix the bug and verify by observing that the test passes.
The bug is related to the initial state: a component created via `wrapWithLocalState` keeps its state using React's own mechanism (i.e. `this.state` / `this.setState`), but it never gives React the _initial_ state, leaving it `undefined`. Instead, it was just coercing `undefined` to `initialState` at time of reading, roughly equivalent to this:
```
let getState = () => this.state ?? calculateInitialState(this.props)
```
This means that _until the first call to `this.setState`_, the component's state is effectively equivalent to whatever is passed in props. Which means that the component's state gets …
=> Fix a bug with initial state in wrapWithLocalState

.editorconfig, CHANGELOG.md, package-lock.json, package.json, packages.dhall, src/Elmish/Component.js, test/Component.purs, test/LocalState.purs
For debugging and testing purposes, it would be useful if different Elmish-generated components weren't all named "ElmishComponent". This was ok before, when we mostly just had one component per app, but now that we're using more and more self-contained event loops, this may become somewhat confusing.
* The "root" components (i.e. ones created via `construct`) are all named `ElmishRoot`.
* The components created via `wrapWithLocalState` are named `Elmish_<name>`, where `<name>` is the `ComponentName` passed to `wrapWithLocalState`.
* At first I considered a colon `Elmish:<name>` instead of underscore `Elmish_<name>`, but colon wouldn't work for selecting such components in Enzyme, e.g. `find "Elmish:Foobar"` - the "Foobar" part here would be interpreted as a CSS assertion rather than part …
=> Give generated React components proper names

.github/workflows/build.yml, CHANGELOG.md, src/Elmish/Dispatch.purs
By suggestion from @mcordova47, making precedence of `<|` and `<?|` zero, so that they can be used like `dispatch <| foo $ stuff $ more $ stuff`. 
This works, even though `$` also has zero precedence, because `<|` and `<?|` are left-associative, while `$` is right-associative, so mixing them in the same expression is allowed.
=> Lowest precedence for <| and <?|

CHANGELOG.md, spago.dhall, src/Elmish/Dispatch.purs
Before this change, the following doesn't compile:
```haskell
onKeyUp: dispatch <?| \(E.KeyboardEvent e) -> guard (e.keyCode == 27) $> Cancel
```
This happens because both `guard` and `$>` work for any functor, so the compiler doesn't know that it's supposed to be `Maybe`, and because it doesn't know, it cannot match the `event -> Maybe msg` instance. The instance can either match or not match depending on whether the unknown functor is `Maybe` or something else. This means that the compiler cannot pick the instance until it knows the functor.
The change in this PR makes the instance match _any_ functor, but after the match is done, it forces the functor to be `Maybe` via a `TypeEquals` constraint. This allows the snippet above to compile.
=> Force Maybe in handleMaybe

CHANGELOG.md, docs/_try/readForeign.1.purs, docs/_try/readForeign.2.purs, docs/read-foreign.md, package-lock.json, package.json, packages.dhall, src/Elmish/Foreign.purs, src/Elmish/Opaque.purs, test/Foreign.purs
It is now possible to visibly-apply type parameters of `readForeign` and `readForeign'`:
```
f :: Foreign
x = readForeign @{ a :: Int, b :: Number } f
```
=> Upgrade PureScript to 0.15.10, port readForeign to visible type applications

CHANGELOG.md, src/Elmish.purs, src/Elmish/Component.js, src/Elmish/Component.purs, src/Elmish/React.js, src/Elmish/React.purs, src/Elmish/Subscription.purs, test.dhall, test/Component.purs, test/Main.purs, test/Subscriptions.purs
Introducing Subscriptions!
Though the name is borrowed from Elm, these work a bit differently: rather than having a fourth function `subscriptions` (alongside `init`, `view`, and `update`), adding a subscription is an effect that can be made part of a state transition, including the initial one in `init`.
Under the hood, the material change is that the `forks` function's parameter callback now takes not only `dispatch` to issue messages, but also an `onStop` function that it can use to react to when the component is unmounted, which is essential to implement the concept of "unsubscribing".
The rest is just facade API: the `Subscription` type is crafted in a way to force the author to provide an "unsubscribe" callback, and encodes the type of messages that "come out" of the subscription; …
=> Subscriptions

CHANGELOG.md, src/Elmish/Component.js, src/Elmish/Component.purs, test/LocalState.purs
The `ComponentDef` is captured in closures defined under `where` in `bindComponent`. In most cases this is fine, because `ComponentDef` is constant anyway. And even if not, `bindComponent` is called on every render, which means a new, fresh value of `ComponentDef` is re-captured on every render.
But what if such closure could survive several renders and several changes of `ComponentDef`? If the closure is a `dispatch` function, the next message that is issued through it will call a stale version of `update`. This is particularly important now that we added subscriptions, which keep the initial value of `dispatch` pretty much indefinitely.
See the new test I added in this PR to see how this could happen. If the changes to `bindComponent` are undone, that test fails in exactly the way the …
=> Avoid capturing ComponentDef in a closure for a long time
